### ISSUE TITLE
Unable to import chips and projects from original game

### ISSUE THREAD

**Issue by 901238746** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#100]
I have made some things in the OG game but I cant import them into it

**Comment by VitoBarra** [comment]
This response applies to this issue and issues #98 and #86. Unfortunately this long time requested feature is not yet supported, so there is no easy way. I suggest either redoing all the chips or waiting until the feature is implemented.

**Comment by 901238746** [comment]
sad

**Comment by 901238746** [comment]
Oh the last update was 2 years ago.
