### ISSUE TITLE
chip import button does nothing on Linux build

### ISSUE THREAD

**Issue by BBQGiraffe** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#13]
the save button works fine but the import button doesn't bring up anything on the Linux build

**Comment by AOx0** [comment]
Thanks for the report. I will look into it.

**Comment by AOx0** [comment]
Update: Commit 55093ae52a19a0afb7a8c60bf3f432386a4e9f07 is intended to fix this issue
