### ISSUE TITLE
Dumb question but is there a place where I can find the controls?

### ISSUE THREAD

**Issue by musicman928** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#14]
I'm confused how to edit a circuit, does anyone know how?

**Comment by musicman928** [comment]
I'm confused how to edit a circuit, does anyone know how?

**Comment by AOx0** [comment]
Hi, to edit an existing custom chip you have to:
  1. Right click its name in the chip bar
  2. Select the view option.
      - Now you should view the chips as it was when you saved it
  3. Make your modifications.
      - Drag anything you need, add inputs, outputs, etc. 
  4. To save the modifications select the "Update" option within the Chip item on the top bar.
