### ISSUE TITLE
Enhancement - View existing chip internals

### ISSUE THREAD

**Issue by SourSpoon** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#27]
The ability to view existing chip internals would be very useful.

Even if this is limited to chips that you have built yourself.

Thanks

**Comment by AOx0** [comment]
Hi @SourSpoon, you can already view chip internals (only for those built by yourself). 

To do it you have to right click on it and select view, here is an example: 

<img width="1680" alt="Screen Shot 2022-08-17 at 3 03 39 p m" src="https://user-images.githubusercontent.com/50227494/185232389-3d6b5427-54a6-4833-a5db-ec2f6bf7cace.png">

Now I can see what does makeup chip `SD2`

<img width="1680" alt="Screen Shot 2022-08-17 at 3 03 43 p m" src="https://user-images.githubusercontent.com/50227494/185232415-dc4f03f3-efd6-4ad7-8ae9-c5f138d517f1.png">

From here it's possible to modify this already saved chip and update it with the option `Chip > Update`

<img width="1680" alt="Screen Shot 2022-08-17 at 3 06 01 p m" src="https://user-images.githubusercontent.com/50227494/185232847-27f32967-c7cf-4c16-8908-8f5a1b486960.png">

Or, to discard any modifications and stop viewing internals you can just select `Exit`

<img width="1680" alt="Screen Shot 2022-08-17 at 3 03 48 p m" src="https://user-images.githubusercontent.com/50227494/185232971-1ac6a75e-aebd-4828-9d7d-af75bf00df12.png">

**Comment by AOx0** [comment]
Let me know if this is indeed the answer you were looking for.

**Comment by SourSpoon** [comment]
Thanks,

This was the answer I was looking for. My Appologies.
