### ISSUE TITLE
Ux General Issues

### ISSUE THREAD

**Issue by SourSpoon** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#28]
![Digital_Logic_Sim_7tFXRloBgI](https://user-images.githubusercontent.com/14321372/186119278-52d35903-1c0c-48b9-874e-7c5030e2970d.gif)

I was pressing return/ enter when I was highlighting the "X" too.

Windows x64
Intel i5 9th
16GB RAM

**Comment by VitoBarra** [comment]
There are some general problems with the UX and I'm planning to work on them as soon as possible. I'll be working on this specific issue first, but in the meantime it should work by clicking on the left vertical blue bar once you finish editing the pin and then clicking anywhere else to close the menu.

Let me know if you stumble across other similar issues.

**Comment by AOx0** [comment]
Nice catch, tbh I never noticed. Keeping up with tests might be nice too

**Comment by SourSpoon** [comment]
@VitoBarra 

Would you like me to create new issues or just bundle them in here?

**Comment by VitoBarra** [comment]
bundled here will be great. maybe you should also rename the issue as "UX general problem". However, I don't know the best practice for this situation. I think @AOx0  could respond to you better

**Comment by SourSpoon** [comment]
![image](https://user-images.githubusercontent.com/14321372/186271088-9b5d2033-7ac5-4dcf-bb83-1da96a46b03d.png)

Getting grouped values to appear can take some poking and prodding. See above image where I have managed to get one to display and one to not.  If there are rules to dictate this it would be nice if they were clear.

**Comment by AOx0** [comment]
The best practice is to keep an issue for each specific problem, it's better for granularity. 

We can keep this thread as an issue tracker by making mention of it on each new issue related to UX, tho. (Although that role is for "GitHub projects")
