### ISSUE TITLE
Bug - Grouped Values UI

### ISSUE THREAD

**Issue by SourSpoon** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#29]
![image](https://user-images.githubusercontent.com/14321372/186271088-9b5d2033-7ac5-4dcf-bb83-1da96a46b03d.png)

Getting grouped values to appear can take some poking and prodding. See above image where I have managed to get one to display and one to not.  If there are rules to dictate this it would be nice if they were clear.

_Originally posted by @SourSpoon in https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/issues/28#issuecomment-1224916528_

**Comment by VitoBarra** [comment]
can you elaborate further? what did you do, specifically, to make this happen?

**Comment by SourSpoon** [comment]
[Just sort of play around with it](https://youtu.be/aw8A4XnKLVs)

Seems strange
