### ISSUE TITLE
Bus wires and wire design

### ISSUE THREAD

**Issue by lian-hsc** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#31]
If a chip is saved and then edited again, some information is lost or is not loaded correctly.
On the one hand, each input or output is always displayed as simple, regardless of which bus was set beforehand.
On the other hand, the wire design is not displayed correctly. Which in itself doesn't matter for the functionality of the chip, but with more complicated larger chips it makes it difficult to change things. However, this error only occurs if two or more wire go out from a starting point.

https://user-images.githubusercontent.com/56408700/187637490-05782ff5-2f89-470c-9a8f-00823f942633.mp4

It would also be cool if you could change and see the value for bus wires. Otherwise you have to create a lot of inputs again at some point.

**Comment by VitoBarra** [comment]
OK, I already noticed this problem but your video gave me some idea so I played around with pins and discovered that the problem exists only with unnamed pins, with the named one everything seems to work fine. So I now know where to see to fix this bug

**Comment by crispeeweevile** [comment]
> OK, I already noticed this problem but your video gave me some idea so I played around with pins and discovered that the problem exists only with unnamed pins, with the named one everything seems to work fine. So I now know where to see to fix this bug

unnamed pins appear to always lose their pin type with no regard to whether they're named or not; however, I have confirmed that the lines themselves only move if the pins are unnamed

**Comment by VitoBarra** [comment]
Update: I Found The bug but I can't fix it without breaking compatibility. There is an association problem between the saved wire layout and the editor wire layout in particular every time there are two or more wires with the same starting and ending point name only one wire perhaps is going to work all the others will be connected only to the start point and the end point.

so to those who want to check out the problem. 
in the script ChipLoader at line 332, there is this 

> int wireIndex = Array.FindIndex(loadedChipData.wires, w =>w.startPin.pinName == startPinName && w.endPin.pinName == endPinName);

 this selects the index of the wire in one array. that line is wrong in the situation I described above.
