### ISSUE TITLE
Can't import old project from original Digital logic sim

### ISSUE THREAD

**Issue by devpour** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#33]
can someone help me with this

**Comment by AOx0** [comment]
Hi, sorry you are having issues. 
This DLS Edition introduces quite some changes to the save system, tho.
Can you provide us the save files and maybe some more details about the original digital logic sim version?

**Comment by 901238746** [comment]
But I still cant do this...

**Comment by 901238746** [comment]
How am I meant to import it
