### ISSUE TITLE
Load breaks when loading chips with missing dependency

### ISSUE THREAD

**Issue by VitoBarra** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#34]
![image](https://user-images.githubusercontent.com/52669351/189947109-33bfd490-aebf-422e-a436-54b117b8898a.png)

**Comment by VitoBarra** [comment]
oops, thanks for the correction

**Comment by crispeeweevile** [comment]
> oops, thanks for the correction

All good, I just wanted to make sure you fully understood the problem at hand
