### ISSUE TITLE
A Travesty! (First bug encountered V0.39, yes I compiled it)

### ISSUE THREAD

**Issue by crispeeweevile** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#41]
A very unfortunate event has occurred in Lego City today, it with a heavy heart that I must announce... The ability to change from simple pin type does not work :p I didn't really  do anything special to encounter this, all I was doing was making "new" encoders (basically just a passthrough the the already existing ones so I can rename them,) but in the process I learned that the ability to change pin type is broken. This is completely- fine. Please fix it whenever you can, but I don't know that anybody's day will be ruined by this fact.

**Comment by AOx0** [comment]
It should be disabled for groups, and enabled for single pins.
Does it work for single pins?

**Comment by AOx0** [comment]
NVM, I see the problem. Thanks for the feedback :/

**Comment by crispeeweevile** [comment]
> NVM, I see the problem. Thanks for the feedback :/

Thanks for getting back to me so quickly :) Hopefully it will be a really quick solution without much to do.

**Comment by AOx0** [comment]
@VitoBarra I think tracked down the issue to commit c2dbe38c9aeecd0af0894e3b77d62bde4f24b19e in file [Assets/Scripts/Interaction/ChipInterfaceEditor.cs](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/commit/c2dbe38c9aeecd0af0894e3b77d62bde4f24b19e#diff-5f49051a73faae1ad437b846388f5e57f975e6d437026f657fd26e690fbccff0)

Here: 
```diff 
-        if (selectedSignals.Count == 0)
+        if (IsSomethingSelected)
```
`IsSomethingSelected` (always?) returns early

https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/blob/646502879423dd1cfe3c062ba785f78cdf32d732/Assets/Scripts/Interaction/ChipInterfaceEditor.cs#L131-L132

I think it should be:
```diff 
-        if (IsSomethingSelected)
+        if (!IsSomethingSelected)
```

Any comments? So I can commit the fix on branch [`v0.39.1-dev`](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/tree/v0.39.1-dev)

Edit: Wrong file link, updated it

**Comment by VitoBarra** [comment]
> 
yes that definitely is a correct fix, but I’m testing it and even so it seems not to work. 
I’m trying to find out what’s going on.

I think it is just a visualization problem now

**Comment by AOx0** [comment]
Hm, it does work fine for me with 87e367c92acddb4438fd345b963331477d11b5c9. By fine I mean now wires do connect to same Pin types, both out and in


<img width="1664" alt="Screenshot 2022-12-04 at 9 38 46 p m" src="https://user-images.githubusercontent.com/50227494/205544245-5064d11a-7a37-4b19-b69a-a7ee3017043b.png">

<img width="1664" alt="Screenshot 2022-12-04 at 9 41 20 p m" src="https://user-images.githubusercontent.com/50227494/205544561-00608498-fb6e-46ae-b6f7-984cb8d9bb3c.png">

**Comment by VitoBarra** [comment]
yep, that works for me too. I was referring to the fact that if you change the wire type and then try to edit again it will show as it is still simple, I don't know if it was  the case also earlier tho

**Comment by AOx0** [comment]
Oh, I see it now. I'm looking into it.

Edit. If you get a working branch make a PR targeting branch `v0.39.1-dev`
