### ISSUE TITLE
disallow using chips that use the current chip `c` as a building block when editing `c`

### ISSUE THREAD

**Issue by HannesGitH** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#47]
do catch recursive loops early on so it wont cause problems later on

in my case i just finished building a 8by8 bit multiplier but then noticed i was currently editing my one-bit adder, so the one bit adder was now a 8by8 multiplier;
as i didnt want to loose my multiplier and couldnt figure out how to undo that i paniced and tried to export it quickly but through the recursive loop that couldnt finish and now i cant open my save anymore and lost it all :/ damn :D 

so yeah disallowing recursive placement early on would be useful ;)

**Comment by crispeeweevile** [comment]
E, I bet that bug has been here a while (though technically one could say it's not a bug)
