### ISSUE TITLE
1Hz clock forgets its connections when compiled

### ISSUE THREAD

**Issue by CDWimmer** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#48]
I made a simple togglable clock by sticking an input line and a 1Hz clock into an AND, which works until it is saved and exported. The new clock chip then does nothing. Right clicking it and viewing it shows me that the wire connecting the clock to the gate has vanished,  and I think the input line becomes bugged too.
 
This is with 0.39.1 x86 64bit on Windows. 

Demo of the chip before saving:

![image](https://user-images.githubusercontent.com/31413434/208311444-8d32fec4-abee-4284-8b64-61d0d234d236.png)

![image](https://user-images.githubusercontent.com/31413434/208311451-8e64e8d4-ea40-4267-9c68-57a51c45339d.png)

Compiled chip not working (just take my word that it isn't toggling on/off here obviously its hard to demo without video): 

![image](https://user-images.githubusercontent.com/31413434/208311514-623896bb-c8c7-4cfe-b45a-5ad720d4b2fc.png)

Clearing that and then going to view the "TOGGLE CLOCK" chip:

connection vanished:
![image](https://user-images.githubusercontent.com/31413434/208311564-a84ae7c4-f768-4330-81db-947ab8e3e4ff.png)

and finally, the input wire being bugged:
![image](https://user-images.githubusercontent.com/31413434/208311576-b6d617fb-4dd8-4b79-aa44-391b46c05469.png)

**Comment by crispeeweevile** [comment]
This actually happens with any chips that do not have both an input AND an output. It has been an issue since the previous version
