### ISSUE TITLE
"Comp" Folder disabled

### ISSUE THREAD

**Issue by SourSpoon** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#58]
Hi,

Sometimes the comp folder is disabled occasionally

![image](https://user-images.githubusercontent.com/14321372/211018334-48011610-61c3-48b4-9684-180c08cec21b.png)

![image](https://user-images.githubusercontent.com/14321372/211018648-81b94f6f-dc9b-4727-9fe7-b6131dc38646.png)

Its really good that you can open up this folder and view what goes into making a half adder and full adder. But sometimes this folder is disabled, what's the criteria for it to be enabled?

Thanks

**Comment by VitoBarra** [comment]
Comp stands for "compatibility", it is a "transient" folder means that every chip that falls there should be moved elsewhere, infants the comp folder is disabled when it is empty.
If this is not the case let me know, maybe there is some problem there that should be investigated

**Comment by SourSpoon** [comment]
Ahh So these are from projects with chips from previous versions of the app.
understood.
