### ISSUE TITLE
Allow direct pin bus modification

### ISSUE THREAD

**Issue by git123userhub** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#62]
Tbh, Im not really comfortable with the fact that you have to decode a bus pin to be able to modify it
Cant there be a binary array panel on each bus pin menu that we can modify, (and a binary array panel on output pins, unmodifiable)? that would really help.

**Comment by pudy248** [comment]
I added the ability to input integers into busses in #59, should hopefully be merged soon. It's not binary, but it would be difficult to fit 32 of anything into a single pin.

**Comment by git123userhub** [comment]
nice! hopefully the merge does happen, but ill keep this issue awake until it comes
