### ISSUE TITLE
Build download

### ISSUE THREAD

**Issue by 2xddev** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#8]
Please release a build that i can download so i can use this awesome fork.

**Comment by AOx0** [comment]
Sure. I will upload a build anytime today.

**Comment by AOx0** [comment]
Ready. Builds are available [here](https://github.com/AOx0/Digital-Logic-Sim-CE/releases/tag/v0.36)

**Comment by AOx0** [comment]
Due to builds being now available, I'm closing this issue. Have a nice day!

**Comment by 404CoderNotFound** [comment]
Thank you!
