### ISSUE TITLE
Some features from the original are not in this version

### ISSUE THREAD

**Issue by OkGamez313** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#85]
Can I change the color of wires or has this feature not been added? it is in the original.

**Comment by OkGamez313** [comment]
Also the cursor guide.

**Comment by crispeeweevile** [comment]
That feature, along with multiple others have yet to be added unfortunately

**Comment by VitoBarra** [comment]
This feature is being added in the PR #79, so this issue should also be closed

**Comment by OkGamez313** [comment]
Thanks.
