### ISSUE TITLE
Is #79 ever gonna get approved

### ISSUE THREAD

**Issue by 901238746** [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#93]
This is a cool merge request but it hasnt been touched in 6 months. please do something about #79

**Comment by AOx0** [comment]
Hi, now that I have some time I will look up to merge the PR and issue a new release.

**Comment by VitoBarra** [comment]
I'm actively working on it to finish the missing feature set out in the PR, so I suggest you wait a few days.

**Comment by AOx0** [comment]
Oh, okay. Thank you very much as always Vito :D!
